[package]
name = "hecto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
synoptic = "1.2.0"
termion = "3.0.0"
unicode-segmentation = "1.10.1"
